---

- name: "configuration play." 
  hosts: web
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  environment:
      - TYPEORM_MIGRATIONS_DIR=./src/migrations
      - TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts
      - TYPEORM_MIGRATIONS=./src/migrations/*.ts
      - TYPEORM_PORT=5432
      - TYPEORM_USERNAME=postgres
      - TYPEORM_PASSWORD=udapeople
      - TYPEORM_DATABASE=postgres
      - TYPEORM_HOST=database-1.cxbh64iub6rq.us-east-2.rds.amazonaws.com

  roles:
    - deploy
