---
  - name: "update apt packages."
    become: yes
    apt:
      update_cache: yes

  - name: "upgrade packages"
    become: yes
    apt:
      upgrade: yes

  - name: "remove dependencies that are no longer required"
    become: yes
    apt:
      autoremove: yes

  - name: "install nodejs and npm"
    become: yes
    apt:
      name: ["nodejs", "npm"]
      state: latest
      update_cache: yes

  - name: "install n"
    become: yes
    npm:
      name: n
      global: yes
      production: yes

  - name: "install nodejs 13.8.0"
    become: yes
    shell: n 13.8.0

  - name: "install pm2"
    become: yes
    npm:
      name: pm2
      global: yes
      production: yes
      state: present

  - name: "move env variables to profile.d"
    become: true
    copy:
      src: /home/circleci/project/.circleci/ansible/roles/configure-server/files/variables.sh
      dest: /etc/profile.d/variables.sh
      mode: a+x

  # - name: Execute the file on the remote host
  #   command: /etc/profile.d/variables.sh

  - name: Execute file and decode output as string
    vars:
      file_path: "/etc/profile.d/variables.sh"
    command: "{{ file_path }}"
    register: output
    changed_when: false

  - set_fact:
      decoded_output: "{{ output.stdout | b64decode }}"
 

