---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: true
  apt:
    upgrade: yes

- name: remove unneeded deps
  become: true
  apt:
    autoremove: yes

- name: install deps
  become: true
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: install pm2
  become: true
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

- name: extract artifact
  become: true
  unarchive:
    src: /home/circleci/project/artifact.tar.gz
    dest: /home/ubuntu

- name: echo environment variables
  become: true
  shell: |

    echo AWS_DEFAULT_REGION=us-east-2 >> ".env"
    echo TYPEORM_CONNECTION=postgres >> ".env"
    echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> ".env"
    echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> ".env"
    echo TYPEORM_MIGRATIONS=./src/migrations/*.ts >> ".env"
    echo TYPEORM_PORT=5432 >> ".env"
    echo TYPEORM_USERNAME=postgres >> ".env"
    echo TYPEORM_PASSWORD=udapeople >> ".env"
    echo TYPEORM_DATABASE=postgres >> ".env"
    echo TYPEORM_HOST=database-1.cxbh64iub6rq.us-east-2.rds.amazonaws.com >> ".env"
    cat .env

- name: start app
  become: true
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
